name=SKK_nano_mcp
version=2.4.3
author=SKK
maintainer=SKK
sentence=Simple global-function MCP3008 sensor and robot motion library for Arduino Nano.
paragraph=Contains MCP3008 front sensor reading, EEPROM calibration, five-menu mission example, motor compensation, servo, line passing and left/right turning functions.
category=Device Control
architectures=avr
depends=Adafruit MCP3008,Adafruit SSD1306,Adafruit GFX Library,Servo
